<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0</TargetFrameworks>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>aceryansoft.sqlflow</PackageId>
    <Description>
      C# light and fluent wrapper to easily use multiple sql databases (Sql server,Oracle,PostgreSql,Mysql,Sybase)
      with the same code while targeting dotnet standard 2.0 , dotnet framework 4.6.1 , dotnet 8 and above.
    </Description>
    <Version>1.0.0.0</Version>
    <Authors>Yannick Cyrille Nganko</Authors>
    <owners>Aceryan consulting</owners>
    <Company>Aceryan consulting</Company>
    <RepositoryUrl>https://github.com/aceryan-consulting/aceryansoft.sqlflow</RepositoryUrl>
    <PackageTags>aceryansoft.sqlflow,aceryansoft,sqlflow,sql</PackageTags>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Copyright>aceryan consulting Copyright 2021</Copyright>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <PackageReleaseNotes>
      Initial package release

    </PackageReleaseNotes>
    <PackageProjectUrl>https://github.com/aceryan-consulting/aceryansoft.sqlflow</PackageProjectUrl>
    <PackageLicenseFile>LICENSE.md</PackageLicenseFile>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
     <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
 
  <ItemGroup>
    <None Include="..\..\LICENSE.md" Pack="true" PackagePath="LICENSE.md" />
     <None Include="..\..\README.md" Pack="true" PackagePath="\" /> 
	  
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>aceryansoft.sqlflow.tests</_Parameter1>
    </AssemblyAttribute> 
  </ItemGroup>
 
  <ItemGroup>
    <PackageReference Include="AdoNetCore.AseClient" Version="0.19.2" />
	  <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="MySql.Data" Version="9.5.0" />
   
   
  </ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="2.19.290" />
		<PackageReference Include="Npgsql" Version="8.0.8" /> 
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.0" />
		<PackageReference Include="Npgsql" Version="8.0.8" /> 
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'net8.0' ">
		<PackageReference Include="Oracle.ManagedDataAccess.Core" Version="23.26.0" />
		<PackageReference Include="Npgsql" Version="9.0.4" /> 
	</ItemGroup>
</Project>
